<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHpyOp7s\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHpyOp7s/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHpyOp7s.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHpyOp7s\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHpyOp7s\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HpyOp7s',
    'container.build_id' => '8ad5ee7d',
    'container.build_time' => 1767442818,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHpyOp7s');
